applications:
    - name: argo-apps
      namespace: argocd
      annotations:
        argocd-image-updater.argoproj.io/image-list: myalias=anzeha/ffantasy.users
        argocd-image-updater.argoproj.io/myalias.update-strategy: latest
      destination:
        namespace: floorball-fantasy
        server: https://kubernetes.default.svc
      project: default
      source:
        path: k8s
        repoURL: https://github.com/anzeha/floorball-fantasy-deployment.git
        targetRevision: main
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
projects: []
applicationsets: []
extensions: []