applications:
    - name: argoapp
      namespace: argocd
      additionalAnnotations: 
        argocd-image-updater.argoproj.io/image-list: myalias=anzeha/ffantasy.users
        argocd-image-updater.argoproj.io/git-branch: main
        argocd-image-updater.argoproj.io/write-back-method: git:secret:default/git-creds
        argocd-image-updater.argoproj.io/myalias.force-update: "true"
      destination:
        namespace: floorball-fantasy
        server: https://kubernetes.default.svc
      project: default
      source:
        path: k8s
        repoURL: https://github.com/anzeha/floorball-fantasy-deployment.git
        targetRevision: main
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
projects: []
applicationsets: []
extensions: []