apiVersion: apps/v1
kind: Deployment
metadata:
  name: floorball-fantasy-api-deployment
  namespace: floorball-fantasy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: floorball-fantasy-api
  template:
    metadata:
      labels:
        app: floorball-fantasy-api
    spec:
      containers:
        - image: anzeha/floorball-fantasy:314b78b
          name: floorball-fantasy-api
          env:
          - name: NODE_ENV
            value: prod
          - name: PG_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: PG_HOST
          - name: PG_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: PG_PORT
          - name: PG_DATABASE
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: PG_DATABASE
          - name: PG_USERNAME
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: PG_USERNAME
          - name: PG_PASSWORD
            value: "password"
          # command: ["./node_modules/typeorm/cli.js migration:run -d ./dist/app.datasource.js"]
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: floorball-fantasy-api
  namespace: floorball-fantasy
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: floorball-fantasy-api