apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: floorball-fantasy-ingress
  namespace: floorball-fantasy
  labels:
    app.kubernetes.io/name: floorball-fantasy-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /users(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: users
            port:
              number: 80
      - path: /game-logic(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: game-logic
            port:
              number: 80
      - path: /game-domain(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: game-domain
            port:
              number: 80
  ingressClassName: nginx
