apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: myapp
  namespace: floorball-fantasy
spec:
  url: postgresql://admin:password@postgres-service.floorball-fantasy:5432/floorball_fantasy?sslmode=disable
  schema:
    sql: |
      CREATE TABLE test (
        id SERIAL PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );